# Generated by Django 5.2.18 on 2026-10-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def register_existing_students(apps, schema_editor):
    Enrollment = apps.get_model('learning', 'Enrollment')
    Registration = apps.get_model('learning', 'StudentRegistration')
    alias = schema_editor.connection.alias
    pairs = Enrollment.objects.using(alias).filter(student__is_staff=False).values_list('student_id', 'course__teacher_id').distinct()
    Registration.objects.using(alias).bulk_create(
        [Registration(student_id=student, teacher_id=teacher) for student, teacher in pairs],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_testassignment_testattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_registrations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher'), name='one_student_registration')],
            },
        ),
        migrations.RunPython(register_existing_students, migrations.RunPython.noop),
    ]
