# Generated by Django 5.2.18 on 2026-10-08 16:09

from django.db import migrations, models


def infer_existing_weeks(apps, schema_editor):
    TestAssignment = apps.get_model('learning', 'TestAssignment')
    for assignment in TestAssignment.objects.using(schema_editor.connection.alias).filter(week__isnull=True).iterator():
        snapshot = assignment.question_snapshot
        if not snapshot or not all(isinstance(q, dict) for q in snapshot):
            continue
        weeks = [q.get('week') for q in snapshot]
        if all(type(week) is int and 1 <= week <= 16 for week in weeks) and len(set(weeks)) == 1:
            TestAssignment.objects.using(schema_editor.connection.alias).filter(pk=assignment.pk).update(week=weeks[0])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='major',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='teaching_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='class_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(infer_existing_weeks, migrations.RunPython.noop),
    ]
