# Generated by Django 5.2.18 on 2026-10-10 09:50

import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lessonpractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('folder', 'Folder'), ('file', 'File / presentation'), ('page', 'Page'), ('link', 'Link'), ('test', 'Quiz / test')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('gray', 'Gray')], default='blue', max_length=12)),
                ('availability', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], default='published', max_length=12)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('lesson_key', models.CharField(blank=True, max_length=32)),
                ('source_key', models.CharField(blank=True, max_length=160, null=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, storage=learning.models.content_file_storage, upload_to=learning.models.content_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='learning.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='learning.contentitem')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_item', to='learning.testassignment')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'indexes': [models.Index(fields=['course', 'parent', 'position'], name='course_content_order')],
                'constraints': [models.UniqueConstraint(fields=('course', 'source_key'), name='one_imported_content_source')],
            },
        ),
    ]
